"""
LLM-as-judge guardrail evaluator.

Uses a fast, small model (llama-3.1-8b-instant) to evaluate the credit report
generated by the primary LLM against four criteria:

  1. factual_grounded   — report only references facts present in source data
  2. tone_calibrated    — report tone matches the numerical risk level
  3. solvency_vs_gov    — report correctly separates solvency risk from governance/compliance risk
  4. format_compliant   — report contains all 5 required sections

Returns a structured dict with per-criterion pass/fail, an overall grade (A–D),
token usage, and a list of specific flags. Falls back gracefully if the eval call fails.
"""

import os
import json
import re
from pathlib import Path
import yaml
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

load_dotenv()

_cfg = yaml.safe_load((Path(__file__).parent / "prompts.yaml").read_text())["guardrail"]
_EVAL_MODEL = _cfg["model"]
_SYSTEM = _cfg["system"].strip()

_REQUIRED_SECTIONS = [
    "EXECUTIVE SUMMARY",
    "CREDIT SCORE INTERPRETATION",
    "RISK FACTOR ANALYSIS",
    "LEGAL AND FINANCIAL POSITION",
    "CREDIT OPINION",
]


def _format_check(report: str) -> bool:
    text = report.upper()
    return all(s in text for s in _REQUIRED_SECTIONS)


def _extract_tokens(resp) -> dict:
    meta = getattr(resp, "usage_metadata", None) or {}
    fallback = getattr(resp, "response_metadata", {}).get("token_usage", {})
    inp = meta.get("input_tokens") or fallback.get("prompt_tokens", 0)
    out = meta.get("output_tokens") or fallback.get("completion_tokens", 0)
    tot = meta.get("total_tokens") or fallback.get("total_tokens", inp + out)
    return {
        "model": _EVAL_MODEL,
        "input": inp,
        "output": out,
        "total": tot,
        "cost_usd": round(
            inp * _cfg["cost_per_1m_input_usd"] / 1_000_000
            + out * _cfg["cost_per_1m_output_usd"] / 1_000_000,
            6,
        ),
    }


def evaluate_report(
    company_name: str,
    profile: dict,
    risk: dict,
    report: str,
) -> dict:
    """
    Evaluate the LLM-generated credit report.
    Returns a guardrail result dict (always returns something even on failure).
    Includes a 'tokens' key with usage and cost for this eval call.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key or not report:
        return _fallback("No API key or empty report")

    format_ok = _format_check(report)

    score = risk.get("credit_score", 0)
    risk_level = risk.get("risk_level", "")
    reasons = risk.get("reasons", [])
    has_insolvency = profile.get("insolvency", {}).get("has_insolvency", False)
    outstanding_charges = profile.get("charges", {}).get("outstanding_count", 0)
    news_count = len(profile.get("recent_news", []))
    lei_status = (profile.get("opencorporates", {}).get("lei_status") or "").upper()

    reasons_block = "; ".join(reasons[:6]) if reasons else "none"

    user = f"""Evaluate this credit report for {company_name}.

SOURCE DATA:
  Credit score: {score}/100
  Risk level: {risk_level}
  Score drivers: {reasons_block}
  Formal insolvency on record: {has_insolvency}
  Outstanding registered charges: {outstanding_charges}
  News articles found: {news_count}
  GLEIF LEI status: {lei_status or 'not found'}

REPORT (first 1800 chars):
{report[:1800]}

Evaluate against exactly these criteria:

factual_grounded: Does the report avoid claiming facts NOT present in the score drivers above?
(False if the report invents specific figures, events, or details not derivable from the source data.)

tone_calibrated: Does the tone match the risk level?
- Low Risk (score ≥68): confident, supportive
- Medium Risk (score 45-67): cautious but not alarming
- High Risk (score <45): serious, but proportionate — NOT catastrophising
(False if the report uses extreme language like "certain to default" or "near-certain collapse" for Medium Risk,
OR if it is dismissive of genuine High Risk signals.)

solvency_vs_gov: Does the report correctly distinguish solvency risk (ability to repay) from governance/compliance risk (AML fines, filing delays, regulatory censures)?
(False if the report uses AML fines or filing lateness as evidence of likely default or insolvency.)

Return this exact JSON (no other text):
{{
  "factual_grounded": true_or_false,
  "tone_calibrated": true_or_false,
  "solvency_vs_gov": true_or_false,
  "flags": ["short description of each issue found; empty list if all pass"]
}}"""

    try:
        llm = ChatGroq(
            groq_api_key=api_key,
            model_name=_EVAL_MODEL,
            temperature=_cfg["temperature"],
            max_tokens=_cfg["max_tokens"],
        )
        resp = llm.invoke([SystemMessage(content=_SYSTEM), HumanMessage(content=user)])
        text = resp.content.strip()

        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m:
            return _fallback("Eval model returned non-JSON")

        result = json.loads(m.group())
        result["format_compliant"] = format_ok

        checks = [
            result.get("factual_grounded", False),
            result.get("tone_calibrated", False),
            result.get("solvency_vs_gov", False),
            format_ok,
        ]
        passed = sum(1 for c in checks if c)
        grade = {4: "A", 3: "B", 2: "C", 1: "D", 0: "D"}.get(passed, "D")
        result["overall_grade"] = grade
        result["passed"] = passed
        result["total"] = 4
        result["eval_model"] = _EVAL_MODEL
        result["tokens"] = _extract_tokens(resp)

        return result

    except Exception as e:
        return _fallback(str(e))


def _fallback(reason: str) -> dict:
    return {
        "factual_grounded": None,
        "tone_calibrated": None,
        "solvency_vs_gov": None,
        "format_compliant": None,
        "overall_grade": "?",
        "passed": 0,
        "total": 4,
        "flags": [f"Guardrail evaluation unavailable: {reason}"],
        "eval_model": _EVAL_MODEL,
        "tokens": {},
    }
